name: Validate Queries (Self-Contained)

on:
  push:
    branches: [main]
    paths:
      - "{{QUERIES_DIR}}/{{LANG}}/**"
  pull_request:
    branches: [main]
    paths:
      - "{{QUERIES_DIR}}/{{LANG}}/**"
  workflow_dispatch:

jobs:
  validate:
    uses: neovim-treesitter/.github/.github/workflows/self-contained-validate.yml@main
    with:
      lang: "{{LANG}}"
      queries-dir: "{{QUERIES_DIR}}"
